csharp/ICT/Common/LogWriter.cs
https://github.com/openpetra/openpetra/issues/19 done
=> Logging Windows Client: rotate the client log file #19 done

inc/nant/OpenPetra.common.xml, inc/nant/OpenPetra.csharp.xml, inc/nanttasks/CompileProject.cs
=> fix appveyor build

csharp/ICT/Petra/Client/MReporting/logic/Calculator.cs
to avoid problems with sending Excel file as email
fixes #57
=> reporting: do not release the UIconnector too early

inc/nant/OpenPetra.tobe.migrated.xml
replace call of deprecated FormsAuthentication.HashPasswordForStoringInConfigFile
=> build with mono4

csharp/ICT/BuildTools/GenerateGlue/CreateClientGlue.cs, csharp/ICT/Common/Remoting/Server/ClientManager.cs, csharp/ICT/Petra/Server/lib/MCommon/Main.cs, csharp/ICT/Petra/Shared/lib/MCommon/Types.cs, csharp/ICT/Petra/Shared/lib/MConference/validation/Conference.Validation.cs, inc/template/src/ClientServerGlue/ClientGlue.Connector.cs, setup/petra0300/standalone/standalone.nsi, setup/setup.build
and some fixes for the standalone OpenPetra
=> build standalone installer with LBS

csharp/ICT/Petra/Client/MFinance/Gui/Gift/UC_GiftBatches.Cancel.ManualCode.cs
fixes https://github.com/openpetra/openpetra/issues/103
=> cancelling gift batches did not work. the change was not sent to the server

csharp/ICT/Petra/Server/lib/MSysMan/UserManagement.cs
=> fix requested change of password. only complain if password is the same as the old password.

inc/nant/OpenPetra.common.xml, inc/nanttasks/NUnitConsole.cs
show an error if nunit test is to be run, but nunit console cannot be found
=> only show warning if nunit is not installed.

csharp/ICT/Petra/Server/lib/MFinance/Common/ServerLookups.cs
=> printing annual receipts: fixing problem with amount in words, currency language

csharp/ICT/Common/CommandLineProcessing.cs, csharp/ICT/Common/CustomAppSettings.cs
AppSettings GetKeys for the bankimport CSV plugin
=> Dev20160408 bankimport improvements

csharp/ICT/Petra/Server/app/WebService/SessionManager.cs, csharp/ICT/Testing/lib/NUnitPetraServer/connectServer.cs
this needs to be called for the NUnit server side tests as well.
=> TUserDefaults.InitializeUnit needs to be called for each user.

.gitignore, i18n/i18n.build, setup/petra0300/remoteclientWin/remote.nsi, setup/petra0300/standalone/standalone.nsi
=> add the french translation to the client installers

csharp/ICT/Common/IO/ImportExportDialogs.cs
new parameter to define default file extension.
this is needed for the new donor letter, for the mail merge
=> ImportExportDialogs: export to Excel file

csharp/ICT/BuildTools/GenerateGlue/CreateServerGlue.cs, csharp/ICT/Common/Remoting/Shared/Serialization.cs, csharp/ICT/Petra/Server/lib/MPartner/web/ModuleSetup.cs
setup partner types and publications
=> Tp 201807 setup partner

csharp/ICT/Common/PasswordHelper.cs, csharp/ICT/Petra/Server/app/WebService/SessionManager.cs, csharp/ICT/Petra/Server/lib/MSysMan/UserManagement.cs, inc/template/email/requestnewpassword_de.txt, inc/template/email/requestnewpassword_en.txt
=> implement functionality to request a new password, forgot password.

csharp/ICT/Common/Remoting/Server/ClientManager.cs
that does not have a sitekey yet
=> Catch Exception when retrieving SiteKey for a fresh database

csharp/ICT/BuildTools/DBXML/dataDefinitionStore.cs, csharp/ICT/BuildTools/GenerateORM/codeGenerationPetra.cs, csharp/ICT/Common/Data/TypedDataAccess.cs
=> use OdbcType BigInt for numbers without decimals

appveyor.yml, csharp/ICT/BuildTools/GenerateSQL/loadMysql.cs, csharp/ThirdParty/ThirdParty.build, setup/petra0300/linuxserver/mysql/OpenPetra.build.config, setup/petra0300/linuxserver/openpetra-server.sh
fixes #441 
use getopenpetra.sh on appveyor
=> disable sqlite and use mysql on appveyor

js-client/locales/en/common.json
This is a proposed fix for issue #382
=> Fix missing translation in LedgerSetup.entry_first_current_period

csharp/ICT/Petra/Server/sql/DefaultMotivations.yml
Hi Timotheus. This is for issue #392 which is also related to issue #248.
=> Added Donations motivation group

csharp/ICT/Petra/Server/app/WebService/SessionManager.cs, csharp/ICT/Petra/Server/lib/MSysMan/UserManagement.cs, csharp/ICT/Petra/Server/lib/MSysMan/web/Settings.cs
=> fixes for SetInitialSysadminEmail

csharp/ICT/Petra/Shared/lib/MPartner/data/PartnerTypedDataSets.xml
=> fix for typed partner dataset.

csharp/ICT/Common/IO/FileHelper.cs, csharp/ICT/Petra/Server/lib/MFinance/Gift/Gift.Receipting.cs
=> fix printing logo and signature in donation receipts

csharp/ICT/Common/IO/Yml2Xml.cs
=> fix exporting database to yaml for pyyaml
